
#ifndef HOOPOETESTINGCONFIGURATIONS_H_
#define HOOPOETESTINGCONFIGURATIONS_H_

#define TESTING
#define PRINTTLM
#define ANTS_ON
#define ANTS_DO_NOT_DEPLOY
#define PRINT_IN_CHECK_FUNCTION			(0)

//#define NOT_USE_ACK_HK
#define TESTS
#define FILE_SYSTEM_NOT_TESTED
//#define TESTING_BRONFELD

#endif /* HOOPOETESTINGCONFIGURATIONS_H_ */
