
#ifndef HOOPOETESTINGCONFIGURATION_H_
#define HOOPOETESTINGCONFIGURATION_H_

#define TESTING
#define PRINTTLM
//#define ANTS_ON
#define ANTS_DO_NOT_DEPLOY

#define PRINT_IN_CHECK (0)
//for tests
//#define NOT_USE_ACK_HK
#define TESTS
#define FILE_SYSTEM_NOT_TESTED
//#define TESTING_BRONFELD
//for tests

#endif /* HOOPOETESTINGCONFIGURATION_H_ */
