
#ifndef HOOPOETESTINGCONFIGURATION_H_
#define HOOPOETESTINGCONFIGURATION_H_

#define TESTING

//#define ANTS_ON
#define ANTS_DO_NOT_DEPLOY

#define PRINT_IN_CHECK (0)
//for tests
//#define NOT_USE_ACK_HK
#define TESTS
#define FILE_SYSTEM_NOT_TESTED
//#define TESTING_BRONFELD
//for tests


// ADCS TESTS
#define PRINTTLM
#define PRINT_MAG_TLM
#define PRINT_ANG_RATE_TLM
#define PRINT_WHEEL_SPEED_TLM

#endif /* HOOPOETESTINGCONFIGURATION_H_ */
