
#ifndef HOOPOETESTINGCONFIGURATIONS_H_
#define HOOPOETESTINGCONFIGURATIONS_H_

#define TESTING
#define PRINTTLM
#define ANTS_ON
#define ANTS_DO_NOT_DEPLOY
#define PRINT_IN_CHECK_FUNCTION			(0)

//#define NOT_USE_ACK_HK
#define TESTS
#define FILE_SYSTEM_NOT_TESTED
//#define TESTING_BRONFELD

//	---- ADCS TEST DEFINES
#define PRINT_MAG_TLM
#define PRINT_ANG_RATE_TLM
#define PRINT_WHEEL_SPEED_TLM
#endif /* HOOPOETESTINGCONFIGURATIONS_H_ */
